name: Package and push
description: Packages and pushes helm charts

inputs:
  charts-repo:
    description: Repository containing helm charts
    required: false
    default: cloudve/helm-charts
  packaging-command:
    description: command used to package chart
    required: false
    default: 'helm package "./$CHART_NAME/" -d "$BASE_DIR/$CHARTS_DIR/charts"'
  chart-name:
    description: Chart name
    required: true
  github-token:
    description: Github token
    required: true
  chart-token:
    description: Chart token
    required: true
  github-context:
    description: Github context
    required: true
  git-branch:
    description: Git branch
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.chart-name }}
    - ${{ inputs.charts-repo }}
    - ${{ inputs.git-branch }}
    - ${{ inputs.github-labels }}
    - ${{ inputs.github-token }}
    - ${{ inputs.chart-token }}
    - ${{ inputs.packaging-command }}
